import { Produkt, ProductType } from './product-card/product-interface';

export const productMock: Produkt[] = [
  // Sneaker
  {
    id: crypto.randomUUID(),
    titel: "Urban Stride",
    beschreibung: 'Stylische Sportschuhe für jede Gelegenheit.',
    bildUrl: "productPictures/sneaker1.jpeg",
    preis: 99.99,
    productType: ProductType.sportSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Speed Racer",
    beschreibung: 'Perfekt für schnelle Läufe.',
    bildUrl: "productPictures/sneaker2.jpeg",
    preis: 119.99,
    productType: ProductType.runningSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "City Walker",
    beschreibung: 'Bequeme Sneaker für lange Spaziergänge.',
    bildUrl: "productPictures/sneaker3.jpeg",
    preis: 89.99,
    productType: ProductType.walkingSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "FlexFit Runner",
    beschreibung: 'Stylische Sportschuhe mit guter Dämpfung.',
    bildUrl: "productPictures/sneaker4.jpeg",
    preis: 109.99,
    productType: ProductType.sportSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Endurance Racer",
    beschreibung: 'Für den anspruchsvollen Läufer.',
    bildUrl: "productPictures/sneaker5.jpeg",
    preis: 129.99,
    productType: ProductType.runningSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Comfort Glide",
    beschreibung: 'Leicht und bequem für lange Tage.',
    bildUrl: "productPictures/sneaker6.jpeg",
    preis: 79.99,
    productType: ProductType.walkingSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Street Warrior",
    beschreibung: 'Sportlich und strapazierfähig.',
    bildUrl: "productPictures/sneaker7.jpeg",
    preis: 99.99,
    productType: ProductType.sportSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Race Pro",
    beschreibung: 'Schnell und leicht, perfekt für Rennen.',
    bildUrl: "productPictures/sneaker8.jpeg",
    preis: 119.99,
    productType: ProductType.runningSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Everyday Hero",
    beschreibung: 'Ideal für den Alltag.',
    bildUrl: "productPictures/sneaker9.jpeg",
    preis: 89.99,
    productType: ProductType.walkingSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "City Explorer",
    beschreibung: 'Modische Sneaker für die Stadt.',
    bildUrl: "productPictures/sneaker10.jpeg",
    preis: 109.99,
    productType: ProductType.sportSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Enduro Glide",
    beschreibung: 'Für jeden Laufstil.',
    bildUrl: "productPictures/sneaker11.jpeg",
    preis: 119.99,
    productType: ProductType.runningSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Urban Trekker",
    beschreibung: 'Bequem und praktisch für alle Strecken.',
    bildUrl: "productPictures/sneaker12.jpeg",
    preis: 89.99,
    productType: ProductType.walkingSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Adventure Pro",
    beschreibung: 'Sportlicher Style für jedes Abenteuer.',
    bildUrl: "productPictures/sneaker13.jpeg",
    preis: 99.99,
    productType: ProductType.sportSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Velocity Racer",
    beschreibung: 'Langlebig und schnell.',
    bildUrl: "productPictures/sneaker14.jpeg",
    preis: 129.99,
    productType: ProductType.runningSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Daily Wanderer",
    beschreibung: 'Komfortabel für lange Spaziergänge.',
    bildUrl: "productPictures/sneaker15.jpeg",
    preis: 79.99,
    productType: ProductType.walkingSneaker,
  },

  // Pullover (Hoodies)
  {
    id: crypto.randomUUID(),
    titel: "Chill Hoodie",
    beschreibung: 'Der perfekte Hoodie für entspannte Tage.',
    bildUrl: "productPictures/hoodie1.jpeg",
    preis: 49.99,
    productType: ProductType.hoodie,
  },
  {
    id: crypto.randomUUID(),
    titel: "Urban Comfort",
    beschreibung: 'Stylischer Hoodie für den urbanen Lifestyle.',
    bildUrl: "productPictures/hoodie2.jpeg",
    preis: 59.99,
    productType: ProductType.hoodie,
  },
  {
    id: crypto.randomUUID(),
    titel: "Street Vibes Hoodie",
    beschreibung: 'Hochwertiger Hoodie für Streetwear-Fans.',
    bildUrl: "productPictures/hoodie3.jpeg",
    preis: 69.99,
    productType: ProductType.hoodie,
  },
  {
    id: crypto.randomUUID(),
    titel: "Cozy Weekend",
    beschreibung: 'Der Hoodie, der dich durch jedes Wochenende begleitet.',
    bildUrl: "productPictures/hoodie4.jpeg",
    preis: 54.99,
    productType: ProductType.hoodie,
  },
  {
    id: crypto.randomUUID(),
    titel: "FlexFit Hoodie",
    beschreibung: 'Bequem und funktional für jedes Abenteuer.',
    bildUrl: "productPictures/hoodie5.jpeg",
    preis: 64.99,
    productType: ProductType.hoodie,
  },
  {
    id: crypto.randomUUID(),
    titel: "Night Chill Hoodie",
    beschreibung: 'Für die kühlen Abende in der Stadt.',
    bildUrl: "productPictures/hoodie6.jpeg",
    preis: 59.99,
    productType: ProductType.hoodie,
  }
];
