import { Produkt, ProductType } from './product-card/product-interface';

export const productMock: Produkt[] = [
  {
    id: crypto.randomUUID(),
    titel: "Lange Sneaker",
    beschreibung: 'Stylische Sportschuhe, nicht von Nike.',
    bildUrl: "productPictures/sneaker1.jpeg",
    preis: 99.99,
    productType: ProductType.sportSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Running Sneaker 2",
    beschreibung: 'Perfekt für schnelle Läufe.',
    bildUrl: "productPictures/sneaker2.jpeg",
    preis: 119.99,
    productType: ProductType.runningSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Walking Sneaker 3",
    beschreibung: 'Bequeme Sneaker für lange Spaziergänge.',
    bildUrl: "productPictures/sneaker3.jpeg",
    preis: 89.99,
    productType: ProductType.walkingSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Lange Sneaker 4",
    beschreibung: 'Stylische Sportschuhe mit guter Dämpfung.',
    bildUrl: "productPictures/sneaker4.jpeg",
    preis: 109.99,
    productType: ProductType.sportSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Running Sneaker 5",
    beschreibung: 'Für den anspruchsvollen Läufer.',
    bildUrl: "productPictures/sneaker5.jpeg",
    preis: 129.99,
    productType: ProductType.runningSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Walking Sneaker 6",
    beschreibung: 'Leicht und bequem für lange Tage.',
    bildUrl: "productPictures/sneaker6.jpeg",
    preis: 79.99,
    productType: ProductType.walkingSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Lange Sneaker 7",
    beschreibung: 'Sportlich und strapazierfähig.',
    bildUrl: "productPictures/sneaker7.jpeg",
    preis: 99.99,
    productType: ProductType.sportSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Running Sneaker 8",
    beschreibung: 'Schnell und leicht, perfekt für Rennen.',
    bildUrl: "productPictures/sneaker8.jpeg",
    preis: 119.99,
    productType: ProductType.runningSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Walking Sneaker 9",
    beschreibung: 'Ideal für den Alltag.',
    bildUrl: "productPictures/sneaker9.jpeg",
    preis: 89.99,
    productType: ProductType.walkingSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Lange Sneaker 10",
    beschreibung: 'Modische Sneaker für die Stadt.',
    bildUrl: "productPictures/sneaker10.jpeg",
    preis: 109.99,
    productType: ProductType.sportSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Running Sneaker 11",
    beschreibung: 'Für jeden Laufstil.',
    bildUrl: "productPictures/sneaker11.jpeg",
    preis: 119.99,
    productType: ProductType.runningSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Walking Sneaker 12",
    beschreibung: 'Bequem und praktisch.',
    bildUrl: "productPictures/sneaker12.jpeg",
    preis: 89.99,
    productType: ProductType.walkingSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Lange Sneaker 13",
    beschreibung: 'Sportlicher Style für jedes Abenteuer.',
    bildUrl: "productPictures/sneaker13.jpeg",
    preis: 99.99,
    productType: ProductType.sportSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Running Sneaker 14",
    beschreibung: 'Langlebig und schnell.',
    bildUrl: "productPictures/sneaker14.jpeg",
    preis: 129.99,
    productType: ProductType.runningSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Walking Sneaker 15",
    beschreibung: 'Komfortabel für lange Spaziergänge.',
    bildUrl: "productPictures/sneaker15.jpeg",
    preis: 79.99,
    productType: ProductType.walkingSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Lange Sneaker 16",
    beschreibung: 'Perfekte Mischung aus Stil und Komfort.',
    bildUrl: "productPictures/sneaker1.jpeg",
    preis: 99.99,
    productType: ProductType.sportSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Running Sneaker 17",
    beschreibung: 'Superleicht für intensive Workouts.',
    bildUrl: "productPictures/sneaker11.jpeg",
    preis: 129.99,
    productType: ProductType.runningSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Walking Sneaker 18",
    beschreibung: 'Bequem und einfach für den Alltag.',
    bildUrl: "productPictures/sneaker8.jpeg",
    preis: 89.99,
    productType: ProductType.walkingSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Lange Sneaker 19",
    beschreibung: 'Hochwertiger Sneaker für aktive Menschen.',
    bildUrl: "productPictures/sneaker7.jpeg",
    preis: 109.99,
    productType: ProductType.sportSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Running Sneaker 20",
    beschreibung: 'Für lange und schnelle Läufe.',
    bildUrl: "productPictures/sneaker12.jpeg",
    preis: 119.99,
    productType: ProductType.runningSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Walking Sneaker 21",
    beschreibung: 'Ergonomisch und bequem.',
    bildUrl: "productPictures/sneaker1.jpeg",
    preis: 79.99,
    productType: ProductType.walkingSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Lange Sneaker 22",
    beschreibung: 'Modisch und komfortabel.',
    bildUrl: "productPictures/sneaker2.jpeg",
    preis: 99.99,
    productType: ProductType.sportSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Running Sneaker 23",
    beschreibung: 'Robust und strapazierfähig.',
    bildUrl: "productPictures/sneaker3.jpeg",
    preis: 129.99,
    productType: ProductType.runningSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Walking Sneaker 24",
    beschreibung: 'Für den aktiven Lifestyle.',
    bildUrl: "productPictures/sneaker4.jpeg",
    preis: 89.99,
    productType: ProductType.walkingSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Lange Sneaker 25",
    beschreibung: 'Lange Haltbarkeit und Tragekomfort.',
    bildUrl: "productPictures/sneaker5.jpeg",
    preis: 109.99,
    productType: ProductType.sportSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Running Sneaker 26",
    beschreibung: 'Dynamischer Komfort für dein Training.',
    bildUrl: "productPictures/sneaker6.jpeg",
    preis: 119.99,
    productType: ProductType.runningSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Walking Sneaker 27",
    beschreibung: 'Ideal für Spaziergänge in der Stadt.',
    bildUrl: "productPictures/sneaker7.jpeg",
    preis: 79.99,
    productType: ProductType.walkingSneaker,
  },
  {
    id: crypto.randomUUID(),
    titel: "Lange Sneaker 28",
    beschreibung: 'Kombination aus Style und Funktion.',
    bildUrl: "productPictures/sneaker8.jpeg",
    preis: 99.99,
    productType: ProductType.sportSneaker,
  }
];
